// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Article is the predicate function for article builders.
type Article func(*sql.Selector)

// Category is the predicate function for category builders.
type Category func(*sql.Selector)

// Game is the predicate function for game builders.
type Game func(*sql.Selector)
